### ISSUE TITLE
different places download to the same filename

### ISSUE THREAD

**Issue by aspiers** [TechForUK/posters#1]
If you put in different places then (at least in Chrome on Android) it pops up a dialog "Do you want to download LoveEU-poster.pdf again?" with options to cancel or download.  If the filename contained the place name (e.g. `LoveEU-poster-London.pdf`) then this would not happen, and it would also avoid slightly ugly filenames like `LoveEU-poster (2).pdf`, which would be somewhat inconvenient for anyone who wants to print out posters for more than one place.

![screenshot_20190213-231728](https://user-images.githubusercontent.com/100738/52751342-063b2100-2fe7-11e9-826e-65cbcdb033af.jpg)

**Comment by adamstamper** [comment]
Great idea! Have added in https://github.com/TechForUK/posters/commit/9722f32b33a26475481dd7a213d3d5b42e4668fc
